version: '3'

services:
  bt-joiner:
    image: linarotechnologies/bt-joiner:latest
    privileged: true
    read_only: true
    restart: always
    network_mode: "host"
    tmpfs:
      - /var/run
      - /var/lock
      - /var/log
    volumes:
      - ${PWD}/bluetooth-6lowpand.conf:/etc/bluetooth/bluetooth_6lowpand.conf
  cf-proxy-coap-http:
    image: linarotechnologies/cf-proxy-coap-http:latest
    read_only: true
    restart: always
    network_mode: "host"
  nginx-http-proxy:
    image: linarotechnologies/nginx:latest
    command: nginx-debug -g 'daemon off;'
    read_only: true
    restart: always
    network_mode: "host"
    extra_hosts:
      - "gitci.com:192.168.1.26"
    tmpfs:
      - /var/run
      - /var/cache/nginx
  mosquitto-minimal:
    image: linarotechnologies/mosquitto:latest
    read_only: true
    restart: always
    volumes:
      - ${PWD}/mosquitto-minimal.conf:/etc/mosquitto/conf.d/mosquitto.conf
      
