version: '3'

services:
  nginx-http-proxy:
    image: linarotechnologies/freeboard:latest
    read_only: true
    restart: always
    network_mode: "host"
    ports:
      - 80:80
    tmpfs:
      - /var/run
      - /var/cache/nginx
    volumes:
      - /tmp/dashboards:/usr/share/nginx/html/dashboards
      - /tmp/dashboards/default.json:/usr/share/nginx/html/default.json
      - /tmp/dashboards/default.json:/usr/share/nginx/html/dashboard.json
    command: sh -c
